spring:
  cloud:
    gateway:
      routes:
        - id: first-service-greeting
          uri: https://localhost:8081/
          predicates:
            - Path= /firstService/greeting
            - Query= name, [a-zA-Z]+
            - Method= GET
          filters:
            - AddRequestHeader= request_header1, header_value1
            - AddRequestParameter= name1, abc
        - id: first-service-headers
          uri: https://localhost:8081/
          predicates:
            - Path= /firstService/headers
            - Method= GET
          filters:
            - AddRequestHeader= request_header1, header_value1
            - AddRequestHeader= request_header2, header_value2

firstservice.path[0]: /firstService/classRoute
firstservice.method[0]: GET
firstservice.header[0]: request_header1, header_value1
firstservice.path[1]: /firstService/classRoute2
firstservice.method[1]: GET
firstservice.header[1]: request_header2, header_value2
